### ISSUE TITLE
DI container can not create ConnectClient

### ISSUE THREAD

**Issue by lxalln** [IsmailHassani/Mollie.Net#26]
In [AddMollieApi](https://github.com/I-Synergy/Mollie.Net/blob/0ea76094ceae0ed6a02e56e95339f9cabdcfaef0/src/Mollie.NetStandard2.0/Extensions/MollieApiClientServiceExtensions.cs#L17), `ConnectClient` is registered as an implementation of `IConnectClient`, but there is no way that the DI container is going to be able to resolve this.

`ConnectClient` has 3 parameters:
```csharp
public ConnectClient(string clientId, string clientSecret, HttpClient httpClient = null)
```

The DI container has no knowledge of how to satisfy `clientId` nor `clientSecret`.

I propose that `ConnectClient` should have a constructor that takes `IOptions<AppSettings>` and that `AppSettings` is extended to include `ClientId` and `ClientSecret`. That way DI would be able to handle the construction of `ConnectClient`

```csharp
public ConnectClient(IOptions<AppSettings> settings, HttpClient httpClient = null)
{
    if (string.IsNullOrWhiteSpace(settings.ClientId))
        throw new ArgumentNullException(nameof (settings.ClientId));
    if (string.IsNullOrWhiteSpace(settings.ClientSecret))
        throw new ArgumentNullException(nameof (settings.ClientSecret));

    this._httpClient = httpClient ?? new HttpClient();
    this._clientSecret = settings.ClientSecret;
    this._clientId = settings.ClientId;
}
```

As it stands, I am going to need to manually construct a `ConnectClient`. 

At the very least, in it's current state, `ConnectClient` should not be registered with the DI container.

**Comment by IsmailHassani** [comment]
If my memory serves me well, there are 2 versions of this library. the .net standard 2 version in fact implements this scenario.
[ClientService.cs](https://github.com/I-Synergy/Mollie.Net/blob/master/src/Mollie.NetStandard2.0/Services/ClientService.cs)

The .net standard 1.0 does not. it's actual the initial copy from which i started this project. 
I don't intend to update this version anymore. Of course if you want you can allways create a PR. ;)
